/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package com.siasun.dianshi.bean;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

import lcm.lcm.LCMDataInputStream;
import lcm.lcm.LCMEncodable;


public final class CmsPadInteraction_ implements LCMEncodable
{
    public long utime;
    public byte commandid;
    public byte robotid;
    public int ndparams;
    public double dparams[];
    public int niparams;
    public int iparams[];
    public int nsparams;
    public String sparams[];
    public long nbparams;
    public byte bparams[];
 
    public CmsPadInteraction_()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x7adce3248d74c673L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(CmsPadInteraction_.class))
            return 0L;
 
        classes.add(CmsPadInteraction_.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.commandid); 
 
        outs.writeByte(this.robotid); 
 
        outs.writeInt(this.ndparams); 
 
        for (int a = 0; a < this.ndparams; a++) {
            outs.writeDouble(this.dparams[a]); 
        }
 
        outs.writeInt(this.niparams); 
 
        for (int a = 0; a < this.niparams; a++) {
            outs.writeInt(this.iparams[a]); 
        }
 
        outs.writeInt(this.nsparams); 
 
        for (int a = 0; a < this.nsparams; a++) {
            __strbuf = new char[this.sparams[a].length()]; this.sparams[a].getChars(0, this.sparams[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        outs.writeLong(this.nbparams); 
 
        if (this.nbparams > 0)
            outs.write(this.bparams, 0, (int) nbparams);
 
    }
 
    public CmsPadInteraction_(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public CmsPadInteraction_(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static CmsPadInteraction_ _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        CmsPadInteraction_ o = new CmsPadInteraction_();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.commandid = ins.readByte();
 
        this.robotid = ins.readByte();
 
        this.ndparams = ins.readInt();
 
        this.dparams = new double[(int) ndparams];
        for (int a = 0; a < this.ndparams; a++) {
            this.dparams[a] = ins.readDouble();
        }
 
        this.niparams = ins.readInt();
 
        this.iparams = new int[(int) niparams];
        for (int a = 0; a < this.niparams; a++) {
            this.iparams[a] = ins.readInt();
        }
 
        this.nsparams = ins.readInt();
 
        this.sparams = new String[(int) nsparams];
        for (int a = 0; a < this.nsparams; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.sparams[a] = new String(__strbuf);
        }
 
        this.nbparams = ins.readLong();
 
        this.bparams = new byte[(int) nbparams];
        ins.readFully(this.bparams, 0, (int) nbparams);
    }
 
    public CmsPadInteraction_ copy()
    {
        CmsPadInteraction_ outobj = new CmsPadInteraction_();
        outobj.utime = this.utime;
 
        outobj.commandid = this.commandid;
 
        outobj.robotid = this.robotid;
 
        outobj.ndparams = this.ndparams;
 
        outobj.dparams = new double[(int) ndparams];
        if (this.ndparams > 0)
            System.arraycopy(this.dparams, 0, outobj.dparams, 0, this.ndparams); 
        outobj.niparams = this.niparams;
 
        outobj.iparams = new int[(int) niparams];
        if (this.niparams > 0)
            System.arraycopy(this.iparams, 0, outobj.iparams, 0, this.niparams); 
        outobj.nsparams = this.nsparams;
 
        outobj.sparams = new String[(int) nsparams];
        if (this.nsparams > 0)
            System.arraycopy(this.sparams, 0, outobj.sparams, 0, this.nsparams); 
        outobj.nbparams = this.nbparams;
 
        outobj.bparams = new byte[(int) nbparams];
        if (this.nbparams > 0)
            System.arraycopy(this.bparams, 0, outobj.bparams, 0, (int) this.nbparams);
        return outobj;
    }

    @Override
    public String toString() {
        return "CmsPadInteraction_{" +
                "commandid=" + commandid +
                ", iparams=" + Arrays.toString(iparams) +
                ", sparams=" + Arrays.toString(sparams) +
                '}';
    }
}

