/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package com.siasun.dianshi.bean;


import com.jeremyliao.liveeventbus.core.LiveEvent;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.ArrayList;

import lcm.lcm.LCMEncodable;

public final class PlanPathResult implements LCMEncodable, LiveEvent {
    public String m_strFrom;
    public String m_strTo;
    public int m_iPathPlanPublicId;
    public int m_iPathPlanPublicSubId;
    public short m_uLayerNumber;
    public byte m_iPathPlanRegionChoose;
    public int m_iPathPlanType;
    public int m_iGloalPathPlanType;
    public int m_iCleanPathPanType;
    public int m_iAddLaser;
    public float m_fGloalPathPlanStartPosBuffer[];
    public float m_fGloalPathPlanGoalPosBuffer[];
    public int m_iRegionNumber;
    public float m_fCleanPathPlanStartPosBuffer[];
    public int m_iRegionPoints;
    public float m_fRegionPointsBuffer[];
    public int m_iPlanResult;
    public String m_strAdditionInfo;
    public int m_iPlanResultMode;
    public int m_iPathSum;
    public byte m_cPathTypeBuffer[];
    public int m_iElementSum;
    public float m_fElementBuffer[];
    public long utime;
    public int ndparams;
    public double dparams[];
    public String sparams;
    public int nfparams;
    public float fparams[];
    public int nlparams;
    public int lparams[];
    public int niparams;
    public byte iparams[];

    public PlanPathResult() {
        m_fGloalPathPlanStartPosBuffer = new float[3];
        m_fGloalPathPlanGoalPosBuffer = new float[3];
        m_fCleanPathPlanStartPosBuffer = new float[3];
    }

    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa3de5b95b138c8a3L;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }

    public static long _hashRecursive(ArrayList<Class<?>> classes) {
        if (classes.contains(PlanPathResult.class)) return 0L;

        classes.add(PlanPathResult.class);
        long hash = LCM_FINGERPRINT_BASE;
        classes.remove(classes.size() - 1);
        return (hash << 1) + ((hash >> 63) & 1);
    }

    public void encode(DataOutput outs) throws IOException {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }

    public void _encodeRecursive(DataOutput outs) throws IOException {
        char[] __strbuf = null;
        __strbuf = new char[this.m_strFrom.length()];
        this.m_strFrom.getChars(0, this.m_strFrom.length(), __strbuf, 0);
        outs.writeInt(__strbuf.length + 1);
        for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]);
        outs.writeByte(0);

        __strbuf = new char[this.m_strTo.length()];
        this.m_strTo.getChars(0, this.m_strTo.length(), __strbuf, 0);
        outs.writeInt(__strbuf.length + 1);
        for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]);
        outs.writeByte(0);

        outs.writeInt(this.m_iPathPlanPublicId);

        outs.writeInt(this.m_iPathPlanPublicSubId);

        outs.writeShort(this.m_uLayerNumber);

        outs.writeByte(this.m_iPathPlanRegionChoose);

        outs.writeInt(this.m_iPathPlanType);

        outs.writeInt(this.m_iGloalPathPlanType);

        outs.writeInt(this.m_iCleanPathPanType);

        outs.writeInt(this.m_iAddLaser);

        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.m_fGloalPathPlanStartPosBuffer[a]);
        }

        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.m_fGloalPathPlanGoalPosBuffer[a]);
        }

        outs.writeInt(this.m_iRegionNumber);

        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.m_fCleanPathPlanStartPosBuffer[a]);
        }

        outs.writeInt(this.m_iRegionPoints);

        for (int a = 0; a < this.m_iRegionPoints; a++) {
            outs.writeFloat(this.m_fRegionPointsBuffer[a]);
        }

        outs.writeInt(this.m_iPlanResult);

        __strbuf = new char[this.m_strAdditionInfo.length()];
        this.m_strAdditionInfo.getChars(0, this.m_strAdditionInfo.length(), __strbuf, 0);
        outs.writeInt(__strbuf.length + 1);
        for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]);
        outs.writeByte(0);

        outs.writeInt(this.m_iPlanResultMode);

        outs.writeInt(this.m_iPathSum);

        if (this.m_iPathSum > 0) outs.write(this.m_cPathTypeBuffer, 0, m_iPathSum);

        outs.writeInt(this.m_iElementSum);

        for (int a = 0; a < this.m_iElementSum; a++) {
            outs.writeFloat(this.m_fElementBuffer[a]);
        }

        outs.writeLong(this.utime);

        outs.writeInt(this.ndparams);

        for (int a = 0; a < this.ndparams; a++) {
            outs.writeDouble(this.dparams[a]);
        }

        __strbuf = new char[this.sparams.length()];
        this.sparams.getChars(0, this.sparams.length(), __strbuf, 0);
        outs.writeInt(__strbuf.length + 1);
        for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]);
        outs.writeByte(0);

        outs.writeInt(this.nfparams);

        for (int a = 0; a < this.nfparams; a++) {
            outs.writeFloat(this.fparams[a]);
        }

        outs.writeInt(this.nlparams);

        for (int a = 0; a < this.nlparams; a++) {
            outs.writeInt(this.lparams[a]);
        }

        outs.writeInt(this.niparams);

        if (this.niparams > 0) outs.write(this.iparams, 0, niparams);

    }

//    public PlanPathResult(byte[] data) throws IOException {
//        this(new LCMDataInputStream(data));
//    }

    public PlanPathResult(DataInput ins) throws IOException {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");

        _decodeRecursive(ins);
    }

//    public static PlanPathResult _decodeRecursiveFactory(DataInput ins) throws IOException {
//        PlanPathResult o = new PlanPathResult();
//        o._decodeRecursive(ins);
//        return o;
//    }

    public void _decodeRecursive(DataInput ins) throws IOException {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt() - 1];
        for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte() & 0xff);
        ins.readByte();
        this.m_strFrom = new String(__strbuf);

        __strbuf = new char[ins.readInt() - 1];
        for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte() & 0xff);
        ins.readByte();
        this.m_strTo = new String(__strbuf);

        this.m_iPathPlanPublicId = ins.readInt();

        this.m_iPathPlanPublicSubId = ins.readInt();

        this.m_uLayerNumber = ins.readShort();

        this.m_iPathPlanRegionChoose = ins.readByte();

        this.m_iPathPlanType = ins.readInt();

        this.m_iGloalPathPlanType = ins.readInt();

        this.m_iCleanPathPanType = ins.readInt();

        this.m_iAddLaser = ins.readInt();

        this.m_fGloalPathPlanStartPosBuffer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.m_fGloalPathPlanStartPosBuffer[a] = ins.readFloat();
        }

        this.m_fGloalPathPlanGoalPosBuffer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.m_fGloalPathPlanGoalPosBuffer[a] = ins.readFloat();
        }

        this.m_iRegionNumber = ins.readInt();

        this.m_fCleanPathPlanStartPosBuffer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.m_fCleanPathPlanStartPosBuffer[a] = ins.readFloat();
        }

        this.m_iRegionPoints = ins.readInt();

        this.m_fRegionPointsBuffer = new float[(int) m_iRegionPoints];
        for (int a = 0; a < this.m_iRegionPoints; a++) {
            this.m_fRegionPointsBuffer[a] = ins.readFloat();
        }

        this.m_iPlanResult = ins.readInt();

        __strbuf = new char[ins.readInt() - 1];
        for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte() & 0xff);
        ins.readByte();
        this.m_strAdditionInfo = new String(__strbuf);

        this.m_iPlanResultMode = ins.readInt();

        this.m_iPathSum = ins.readInt();

        this.m_cPathTypeBuffer = new byte[(int) m_iPathSum];
        ins.readFully(this.m_cPathTypeBuffer, 0, m_iPathSum);
        this.m_iElementSum = ins.readInt();

        this.m_fElementBuffer = new float[(int) m_iElementSum];
        for (int a = 0; a < this.m_iElementSum; a++) {
            this.m_fElementBuffer[a] = ins.readFloat();
        }

        this.utime = ins.readLong();

        this.ndparams = ins.readInt();

        this.dparams = new double[(int) ndparams];
        for (int a = 0; a < this.ndparams; a++) {
            this.dparams[a] = ins.readDouble();
        }

        __strbuf = new char[ins.readInt() - 1];
        for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte() & 0xff);
        ins.readByte();
        this.sparams = new String(__strbuf);

        this.nfparams = ins.readInt();

        this.fparams = new float[(int) nfparams];
        for (int a = 0; a < this.nfparams; a++) {
            this.fparams[a] = ins.readFloat();
        }

        this.nlparams = ins.readInt();

        this.lparams = new int[(int) nlparams];
        for (int a = 0; a < this.nlparams; a++) {
            this.lparams[a] = ins.readInt();
        }

        this.niparams = ins.readInt();

        this.iparams = new byte[(int) niparams];
        ins.readFully(this.iparams, 0, niparams);
    }

//    public PlanPathResult copy() {
//        PlanPathResult outobj = new PlanPathResult();
//        outobj.m_strFrom = this.m_strFrom;
//
//        outobj.m_strTo = this.m_strTo;
//
//        outobj.m_iPathPlanPublicId = this.m_iPathPlanPublicId;
//
//        outobj.m_iPathPlanPublicSubId = this.m_iPathPlanPublicSubId;
//
//        outobj.m_uLayerNumber = this.m_uLayerNumber;
//
//        outobj.m_iPathPlanRegionChoose = this.m_iPathPlanRegionChoose;
//
//        outobj.m_iPathPlanType = this.m_iPathPlanType;
//
//        outobj.m_iGloalPathPlanType = this.m_iGloalPathPlanType;
//
//        outobj.m_iCleanPathPanType = this.m_iCleanPathPanType;
//
//        outobj.m_iAddLaser = this.m_iAddLaser;
//
//        outobj.m_fGloalPathPlanStartPosBuffer = new float[(int) 3];
//        System.arraycopy(this.m_fGloalPathPlanStartPosBuffer, 0, outobj.m_fGloalPathPlanStartPosBuffer, 0, 3);
//        outobj.m_fGloalPathPlanGoalPosBuffer = new float[(int) 3];
//        System.arraycopy(this.m_fGloalPathPlanGoalPosBuffer, 0, outobj.m_fGloalPathPlanGoalPosBuffer, 0, 3);
//        outobj.m_iRegionNumber = this.m_iRegionNumber;
//
//        outobj.m_fCleanPathPlanStartPosBuffer = new float[(int) 3];
//        System.arraycopy(this.m_fCleanPathPlanStartPosBuffer, 0, outobj.m_fCleanPathPlanStartPosBuffer, 0, 3);
//        outobj.m_iRegionPoints = this.m_iRegionPoints;
//
//        outobj.m_fRegionPointsBuffer = new float[(int) m_iRegionPoints];
//        if (this.m_iRegionPoints > 0)
//            System.arraycopy(this.m_fRegionPointsBuffer, 0, outobj.m_fRegionPointsBuffer, 0, this.m_iRegionPoints);
//        outobj.m_iPlanResult = this.m_iPlanResult;
//
//        outobj.m_strAdditionInfo = this.m_strAdditionInfo;
//
//        outobj.m_iPlanResultMode = this.m_iPlanResultMode;
//
//        outobj.m_iPathSum = this.m_iPathSum;
//
//        outobj.m_cPathTypeBuffer = new byte[(int) m_iPathSum];
//        if (this.m_iPathSum > 0)
//            System.arraycopy(this.m_cPathTypeBuffer, 0, outobj.m_cPathTypeBuffer, 0, this.m_iPathSum);
//        outobj.m_iElementSum = this.m_iElementSum;
//
//        outobj.m_fElementBuffer = new float[(int) m_iElementSum];
//        if (this.m_iElementSum > 0)
//            System.arraycopy(this.m_fElementBuffer, 0, outobj.m_fElementBuffer, 0, this.m_iElementSum);
//        outobj.utime = this.utime;
//
//        outobj.ndparams = this.ndparams;
//
//        outobj.dparams = new double[(int) ndparams];
//        if (this.ndparams > 0) System.arraycopy(this.dparams, 0, outobj.dparams, 0, this.ndparams);
//        outobj.sparams = this.sparams;
//
//        outobj.nfparams = this.nfparams;
//
//        outobj.fparams = new float[(int) nfparams];
//        if (this.nfparams > 0) System.arraycopy(this.fparams, 0, outobj.fparams, 0, this.nfparams);
//        outobj.nlparams = this.nlparams;
//
//        outobj.lparams = new int[(int) nlparams];
//        if (this.nlparams > 0) System.arraycopy(this.lparams, 0, outobj.lparams, 0, this.nlparams);
//        outobj.niparams = this.niparams;
//
//        outobj.iparams = new byte[(int) niparams];
//        if (this.niparams > 0) System.arraycopy(this.iparams, 0, outobj.iparams, 0, this.niparams);
//        return outobj;
//    }

}

