/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package com.siasun.dianshi.bean;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.ArrayList;

import lcm.lcm.LCMDataInputStream;
import lcm.lcm.LCMEncodable;

public final class PlanPathControlCommand implements LCMEncodable
{
    public String m_strFrom;
    public String m_strTo;

    public int m_iPathPlanPublicId;
    public int m_iPathPlanPublicSubId;
    public short m_uLayerNumber;
    public byte m_iPathPlanRegionChoose;
    public int m_iPathPlanType;
    public int m_iGloalPathPlanType;
    public int m_iCleanPathPanType;
    public int m_iAddLaser;
    public float m_fGloalPathPlanStartPosBuffer[];
    public float m_fGloalPathPlanGoalPosBuffer[];
    public int m_iRegionNumber;
    public float m_fCleanPathPlanStartPosBuffer[];
    public int m_iRegionPoints;
    public float m_fRegionPointsBuffer[];
 
    public PlanPathControlCommand()
    {
        m_fGloalPathPlanStartPosBuffer = new float[3];
        m_fGloalPathPlanGoalPosBuffer = new float[3];
        m_fCleanPathPlanStartPosBuffer = new float[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6b6d5da29dde2b8cL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(PlanPathControlCommand.class))
            return 0L;
 
        classes.add(PlanPathControlCommand.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[this.m_strFrom.length()]; this.m_strFrom.getChars(0, this.m_strFrom.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.m_strTo.length()]; this.m_strTo.getChars(0, this.m_strTo.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.m_iPathPlanPublicId); 
 
        outs.writeInt(this.m_iPathPlanPublicSubId); 
 
        outs.writeShort(this.m_uLayerNumber); 
 
        outs.writeByte(this.m_iPathPlanRegionChoose); 
 
        outs.writeInt(this.m_iPathPlanType); 
 
        outs.writeInt(this.m_iGloalPathPlanType); 
 
        outs.writeInt(this.m_iCleanPathPanType); 
 
        outs.writeInt(this.m_iAddLaser); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.m_fGloalPathPlanStartPosBuffer[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.m_fGloalPathPlanGoalPosBuffer[a]); 
        }
 
        outs.writeInt(this.m_iRegionNumber); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeFloat(this.m_fCleanPathPlanStartPosBuffer[a]); 
        }
 
        outs.writeInt(this.m_iRegionPoints); 
 
        for (int a = 0; a < this.m_iRegionPoints; a++) {
            outs.writeFloat(this.m_fRegionPointsBuffer[a]); 
        }
 
    }
 
    public PlanPathControlCommand(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public PlanPathControlCommand(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static PlanPathControlCommand _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        PlanPathControlCommand o = new PlanPathControlCommand();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.m_strFrom = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.m_strTo = new String(__strbuf);
 
        this.m_iPathPlanPublicId = ins.readInt();
 
        this.m_iPathPlanPublicSubId = ins.readInt();
 
        this.m_uLayerNumber = ins.readShort();
 
        this.m_iPathPlanRegionChoose = ins.readByte();
 
        this.m_iPathPlanType = ins.readInt();
 
        this.m_iGloalPathPlanType = ins.readInt();
 
        this.m_iCleanPathPanType = ins.readInt();
 
        this.m_iAddLaser = ins.readInt();
 
        this.m_fGloalPathPlanStartPosBuffer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.m_fGloalPathPlanStartPosBuffer[a] = ins.readFloat();
        }
 
        this.m_fGloalPathPlanGoalPosBuffer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.m_fGloalPathPlanGoalPosBuffer[a] = ins.readFloat();
        }
 
        this.m_iRegionNumber = ins.readInt();
 
        this.m_fCleanPathPlanStartPosBuffer = new float[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.m_fCleanPathPlanStartPosBuffer[a] = ins.readFloat();
        }
 
        this.m_iRegionPoints = ins.readInt();
 
        this.m_fRegionPointsBuffer = new float[(int) m_iRegionPoints];
        for (int a = 0; a < this.m_iRegionPoints; a++) {
            this.m_fRegionPointsBuffer[a] = ins.readFloat();
        }
 
    }
 
    public PlanPathControlCommand copy()
    {
        PlanPathControlCommand outobj = new PlanPathControlCommand();
        outobj.m_strFrom = this.m_strFrom;
 
        outobj.m_strTo = this.m_strTo;
 
        outobj.m_iPathPlanPublicId = this.m_iPathPlanPublicId;
 
        outobj.m_iPathPlanPublicSubId = this.m_iPathPlanPublicSubId;
 
        outobj.m_uLayerNumber = this.m_uLayerNumber;
 
        outobj.m_iPathPlanRegionChoose = this.m_iPathPlanRegionChoose;
 
        outobj.m_iPathPlanType = this.m_iPathPlanType;
 
        outobj.m_iGloalPathPlanType = this.m_iGloalPathPlanType;
 
        outobj.m_iCleanPathPanType = this.m_iCleanPathPanType;
 
        outobj.m_iAddLaser = this.m_iAddLaser;
 
        outobj.m_fGloalPathPlanStartPosBuffer = new float[(int) 3];
        System.arraycopy(this.m_fGloalPathPlanStartPosBuffer, 0, outobj.m_fGloalPathPlanStartPosBuffer, 0, 3); 
        outobj.m_fGloalPathPlanGoalPosBuffer = new float[(int) 3];
        System.arraycopy(this.m_fGloalPathPlanGoalPosBuffer, 0, outobj.m_fGloalPathPlanGoalPosBuffer, 0, 3); 
        outobj.m_iRegionNumber = this.m_iRegionNumber;
 
        outobj.m_fCleanPathPlanStartPosBuffer = new float[(int) 3];
        System.arraycopy(this.m_fCleanPathPlanStartPosBuffer, 0, outobj.m_fCleanPathPlanStartPosBuffer, 0, 3); 
        outobj.m_iRegionPoints = this.m_iRegionPoints;
 
        outobj.m_fRegionPointsBuffer = new float[(int) m_iRegionPoints];
        if (this.m_iRegionPoints > 0)
            System.arraycopy(this.m_fRegionPointsBuffer, 0, outobj.m_fRegionPointsBuffer, 0, this.m_iRegionPoints); 
        return outobj;
    }
 
}

