/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package com.siasun.dianshi.bean;

import java.io.DataInput;
import java.io.DataOutput;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;

import lcm.lcm.LCMDataInputStream;
import lcm.lcm.LCMEncodable;

public final class robot_control_t_new implements LCMEncodable {
    public long utime;
    public byte commandid;
    public byte robotid;
    public int ndparams;
    public double dparams[];
    public byte niparams;
    public byte iparams[];
    public byte nsparams;
    public String sparams[];
    public long nbparams;
    public byte bparams[];

    public robot_control_t_new() {
    }

    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x3d42b3acebdf8324L;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }

    public static long _hashRecursive(ArrayList<Class<?>> classes) {
        if (classes.contains(robot_control_t_new.class))
            return 0L;

        classes.add(robot_control_t_new.class);
        long hash = LCM_FINGERPRINT_BASE;
        classes.remove(classes.size() - 1);
        return (hash << 1) + ((hash >> 63) & 1);
    }

    public void encode(DataOutput outs) throws IOException {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }

    public void _encodeRecursive(DataOutput outs) throws IOException {
        char[] __strbuf = null;
        outs.writeLong(this.utime);

        outs.writeByte(this.commandid);

        outs.writeByte(this.robotid);

        outs.writeInt(this.ndparams);

        for (int a = 0; a < this.ndparams; a++) {
            outs.writeDouble(this.dparams[a]);
        }

        outs.writeByte(this.niparams);

        if (this.niparams > 0)
            outs.write(this.iparams, 0, niparams);

        outs.writeByte(this.nsparams);

        for (int a = 0; a < this.nsparams; a++) {
            __strbuf = new char[this.sparams[a].length()];
            this.sparams[a].getChars(0, this.sparams[a].length(), __strbuf, 0);
            outs.writeInt(__strbuf.length + 1);
            for (int _i = 0; _i < __strbuf.length; _i++) {
                outs.write(__strbuf[_i]);
            }
            outs.writeByte(0);
        }

        outs.writeLong(this.nbparams);

        if (this.nbparams > 0)
            outs.write(this.bparams);

    }

    public robot_control_t_new(byte[] data) throws IOException {
        this(new LCMDataInputStream(data));
    }

    public robot_control_t_new(DataInput ins) throws IOException {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");

        _decodeRecursive(ins);
    }

    public static robot_control_t_new _decodeRecursiveFactory(DataInput ins) throws IOException {
        robot_control_t_new o = new robot_control_t_new();
        o._decodeRecursive(ins);
        return o;
    }

    public void _decodeRecursive(DataInput ins) throws IOException {
        char[] __strbuf = null;
        this.utime = ins.readLong();

        this.commandid = ins.readByte();

        this.robotid = ins.readByte();

        this.ndparams = ins.readInt();

        this.dparams = new double[(int) ndparams];
        for (int a = 0; a < this.ndparams; a++) {
            this.dparams[a] = ins.readDouble();
        }

        this.niparams = ins.readByte();

        this.iparams = new byte[(int) niparams];
        ins.readFully(this.iparams, 0, niparams);
        this.nsparams = ins.readByte();

        this.sparams = new String[(int) nsparams];
        for (int a = 0; a < this.nsparams; a++) {
            __strbuf = new char[ins.readInt() - 1];
            for (int _i = 0; _i < __strbuf.length; _i++) {
                __strbuf[_i] = (char) (ins.readByte() & 0xff);

            }
            ins.readByte();
            this.sparams[a] = new String(__strbuf);
        }

        this.nbparams = ins.readLong();

        this.bparams = new byte[(int) nbparams];
        ins.readFully(this.bparams);
    }

    public robot_control_t_new copy() {
        robot_control_t_new outobj = new robot_control_t_new();
        outobj.utime = this.utime;

        outobj.commandid = this.commandid;

        outobj.robotid = this.robotid;

        outobj.ndparams = this.ndparams;

        outobj.dparams = new double[(int) ndparams];
        if (this.ndparams > 0)
            System.arraycopy(this.dparams, 0, outobj.dparams, 0, this.ndparams);
        outobj.niparams = this.niparams;

        outobj.iparams = new byte[(int) niparams];
        if (this.niparams > 0)
            System.arraycopy(this.iparams, 0, outobj.iparams, 0, this.niparams);
        outobj.nsparams = this.nsparams;

        outobj.sparams = new String[(int) nsparams];
        if (this.nsparams > 0)
            System.arraycopy(this.sparams, 0, outobj.sparams, 0, this.nsparams);
        outobj.nbparams = this.nbparams;

        outobj.bparams = new byte[(int) nbparams];
        if (this.nbparams > 0)
            System.arraycopy(this.bparams, 0, outobj.bparams, 0, (int) this.nbparams);
        return outobj;
    }

    @Override
    public String toString() {
        return "robot_control_t_new{" +
                "utime=" + utime +
                ", commandid=" + commandid +
                ", robotid=" + robotid +
                ", ndparams=" + ndparams +
                ", dparams=" + Arrays.toString(dparams) +
                ", niparams=" + niparams +
                ", iparams=" + Arrays.toString(iparams) +
                ", nsparams=" + nsparams +
                ", sparams=" + Arrays.toString(sparams) +
                ", nbparams=" + nbparams +
                ", bparams=" + Arrays.toString(bparams) +
                '}';
    }
}

